# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "project-terraform-tfstate"
    encrypt = true
    key     = "production/infrastructure/datasources/terraform.tfstate"
    region  = "eu-central-1"
  }
}
